### ISSUE TITLE
sleep and wakeup :maybe can change AAPL,ig-platform-id

### ISSUE THREAD

**Issue by imnpc** [pexcn/hackintosh-fujitsu-lifebook-u938#1]
AAPL,ig-platform-id:04002759
device-id:16590000
AAPL,GfxYTile:01000000

after wakeup the screen will slowly.

**Comment by pexcn** [comment]
Set `AAPL,ig-platform-id` to `05001C59` will fix it, see more: https://github.com/pexcn/hackintosh-fujitsu-lifebook-u938/commit/5edb1cab236bba4c272242471e8730c8ddf27f55.
