### ISSUE TITLE
BIOS Settings

### ISSUE THREAD

**Issue by sbarbara** [pexcn/hackintosh-fujitsu-lifebook-u938#12]
Can you please include the BIOS settings you changed in the Product desciption as well?

**Comment by pexcn** [comment]
See README: https://github.com/pexcn/hackintosh-fujitsu-lifebook-u938#unlock-bios-settings

**Comment by sbarbara** [comment]
Hi 

Thanks for your reply... I already saw that. What I meant was for example Secure Boot, VT-d, TPM etc... What should those settings be? From the BIOS accessed by pressing F2. Hope it is clearer now.

Thanks

**Comment by pexcn** [comment]
Here's everything I know about this model. (excerpt from my notes)
You can translate and read it yourself.

---

# U938 BIOS 设置

## 特殊键

- `F2` 进入 BIOS
- `F12` 进入选择启动项界面

## 恢复默认设置

开机按 `F2` 键进入 BIOS, `F9` 回车，`F10` 回车。

### 清除 BIOS 密码

1. 开机按 `F2` 进入 BIOS
2. 分别输入 `3hqgo3` 回车，`jqw534` 回车，`0qww294e` 回车
3. 记录下弹窗出现的代码，访问 bios-pw.org 进行解密

## 调整设置

### 最佳设置

先逐项按需配置，再使用 [`setup_var.efi`](https://github.com/datasone/setup_var.efi) 调整。

```sh
# BIOS Lock
setup_var.efi PchSetup:0x17=0x00

# CFG Lock
setup_var.efi CpuSetup:0x3C=0x00

# Package Power Limit MSR Lock
setup_var.efi CpuSetup:0x29=0x00

# Above 4GB MMIO BIOS assignment
setup_var.efi SaSetup:0xE4=0x01

# Intel(R) SGX
setup_var.efi CpuSetup:0xF2=0x00

# DVMT Pre-Allocated
setup_var.efi SaSetup:0xDF=0x02
# DVMT Total Gfx Mem (Don't set it, it will cause OpenCore to unable show boot menu)
#setup_var.efi SaSetup:0xE0=0x03

# Low Power S0 Idle Capability
#setup_var.efi SystemConfig:0x1F1=0x01
# EC Low Power Mode
#setup_var.efi SystemConfig:0x203=0x01
```

### 核心降压

```sh
#
# Not working, maybe it's overridden by the EC settings.
# Use https://github.com/pexcn/IntelVoltageControl#task-scheduler instead.
#

# OverClocking Feature
setup_var.efi CpuSetup:0x1AC=0x01
# Overclocking Lock
setup_var.efi CpuSetup:0xEB=0x00
# Processor -> Offset Prefix
setup_var.efi CpuSetup:0x1B4=0x01
# Processor -> Core Voltage Offset
setup_var.efi CpuSetup:0x1B2(2)=0x64
# GT -> Offset Prefix
setup_var.efi SaSetup:0x1B7=0x01
# GT -> GT Voltage Offset
setup_var.efi SaSetup:0x1B5(2)=0x32
# GTU -> Offset Prefix
setup_var.efi SaSetup:0x1C0=0x01
# GTU -> GTU Voltage Offset
setup_var.efi SaSetup:0x1BE(2)=0x32
```

### 调整温度墙

```sh
# Tcc Activation Offset
setup_var.efi CpuSetup:0x7B=0x05
```

## 调整 MSR

把以下命令编写成脚本并添加到计划任务，触发器设置如下：

1. 设置为 `登录时`, 延迟任务时间 `10 秒`
2. 设置为 `发生事件时`, 源为 `Kernel-Power` 并设置从睡眠唤醒的事件 ID, 延迟任务时间 `10 秒`
3. 设置为 `发生事件时`, 源为 `Kernel-Power` 并设置电源更改的事件 ID, 延迟任务时间 `10 秒`

```bat
:: PL1 (22W, 3584s)
:: PL2 (50W)
msr-cmd.exe write 0x610 0x428190 0xEB80B0
physram.exe write64 0xFED159A0 0x42819000EB80B0

:: PL1 (22W, 3584s, disable clamp)
:: PL2 (50W)
::msr-cmd.exe write 0x610 0x428190 0xEA80B0
::physram.exe write64 0xFED159A0 0x42819000EA80B0

:: CPU Core (-100 mV)
::msr-cmd.exe write 0x150 0x80000011 0xF3400000
:: CPU Cache (-100 mV)
::msr-cmd.exe write 0x150 0x80000211 0xF3400000
:: iGPU Slice (-50 mV)
::msr-cmd.exe write 0x150 0x80000111 0xF9A00000
:: iGPU Unslice (-50 mV)
::msr-cmd.exe write 0x150 0x80000311 0xF9A00000
```

**Comment by sbarbara** [comment]
Hi again.

I managed to set the commands in Opencore openshell and Osx Sonoma booted and is working like a charm. WIFI and bluetooth working out of the box?????!!!! Incredible man... Great job with the EFI setup, I am truly amazed. Can't believe how much the laptop is great for Osx. 

One thing I noticed though after the commands issued is that I cannot get into the BIOS of the laptop. Although I think it is in the background it is not showing up on screen Same for the logs while OSX is booting. Then after some time the apple logo appears and OSX login is shown. It is not related to verbose mode as I did not change anything related to that.

**Comment by pexcn** [comment]
> I cannot get into the BIOS of the laptop

Try after shutting down completely, quickly click F2 when turning on the computer.

**Comment by sbarbara** [comment]
Already did that but nothing is displayed even though I am sure I am in the BIOS... Strange behavior... Can I somehow revert the commands I issued from Open Shell?

**Comment by pexcn** [comment]
Not sure, I've never encountered this problem.
