### ISSUE TITLE
setup_var_efi application cannot be run in Win32 mode

### ISSUE THREAD

**Issue by sbarbara** [pexcn/hackintosh-fujitsu-lifebook-u938#9]
Hi I know it is not directly related but cannot update BIOS without this working. By the way great job and just in time as I am trying to Hackintosh this machine

**Comment by pexcn** [comment]
`setup_var.efi` can only be run in the environment in the UEFI Shell, so you should into OpenShell and execute those commands:
```sh
fs0:
cd EFI/OC/Tools
setup_var.efi --help
```

**Comment by sbarbara** [comment]
Thanks for your reply... I have the same laptop but I7. Are the commands safe to use on it? By the way I have this laptop available for testing if you want... Send me and involve me as much as you need... ;-)

**Comment by pexcn** [comment]
My BIOS version is `1.30`, if yours is too, then it should work, but it's best to unpack your bios to confirm.
